# Generated by Django 5.0.7 on 2024-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_form_user_data_age_alter_form_user_data_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_info',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
