# Generated by Django 5.0.7 on 2024-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_movie_info_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_info',
            name='desc',
            field=models.TextField(),
        ),
    ]
